### ISSUE TITLE
gather different sounds

### ISSUE THREAD

**Issue by octoshrimpy** [octoshrimpy/cognii#3]
get together at least 5 different sound files for each sound type:

fire crackle
rain
thunder booming (hopefully without rain)
wind
ocean
seagulls
brook/river

make sure each file is at least a minute. it can be pulled from a video, as long as the video isn't looped.

**Comment by aLiteralBrick** [comment]
I created a folder in google drive to share sounds & other things
[https://drive.google.com/drive/folders/1KsUNAxa3WknANE8yJ6SwG3MG5dG2G7bb?usp=sharing](url)

sounds added so far:
Fire : 3 options
Rain : 1 option
